### ISSUE TITLE
0.0.15 release date?

### ISSUE THREAD

**Issue by ZogStriP** [phlex-ruby/morphlex#27]
First of all thank you for this amazing little library @joeldrapper 👏 

I'm [working on](https://github.com/discourse/discourse/pull/26138) replacing `diffhtml` with `morphlex` in Discourse. 

From my benchmarks, `0.0.14` is a **22x** speedup 🚀 over `diffhtml` and I'd love to know when you think you'll release version `0.0.15` as I'd love to benchmark these latest changes you've added?

Thanks

**Comment by joeldrapper** [comment]
Hey, that‘s awesome! I had no idea anyone was using this yet. I just released `0.0.15`. I’d love to see your benchmarks, especially on `0.0.15`.

**Comment by ZogStriP** [comment]
Thanks, will run them early next week and keeps you posted 👍

**Comment by joeldrapper** [comment]
Thanks @ZogStriP.

**Comment by ZogStriP** [comment]
> From my benchmarks, `0.0.14` is a **22x** speedup 🚀 over `diffhtml`

Ok, so those numbers are wrong. They were benchmarking `requireAnimationFrame`... 

Totally my fault for not catching it 🤦‍♂️

---

I re-ran the benchmarks using https://github.com/google/tachometer and version `0.0.15` and overall, `morphlex` is a **2-6x** speedup 🚀  over `diffhtml` depending on how large the diff is. Which is even more impressive when `morphlex` is **~1/5th** of `diffhtml` in filesize.

> :memo: All the benchmarks were run on my MacBook Pro 14" 2021 M1 Max w/ 10 CPUs and 32GB of RAM, running macOS Sonoma 14.4 (23E214) and Chrome version 123.0.6312.107

- **baseline** is doing `preview.innerHTML = html`
- **diffhtml** is doing `diff.innerHTML(preview, new.innerHTML)`
- **morphlex** is doing `morphlex.morph(preview, new)`

## Test 1 - empty preview → typing 1st letter

![00991016a681425e75d4dc7bfc7de70c0b4c0a67](https://github.com/phlex-ruby/morphlex/assets/362783/2e533b0a-cc3e-4c6f-aaa1-79e68f0d9505)

## Test 2 - empty preview → pasting 1 paragraph

![becd9c49ba51c01b525efa9290e31005decf0ecd](https://github.com/phlex-ruby/morphlex/assets/362783/2e6bfa3e-c35c-4b38-ac93-8b57a9f1720f)

## Test 3 - empty preview → pasting long post (*our [Getting Started guide](https://github.com/discourse/discourse/blob/main/docs/ADMIN-QUICK-START-GUIDE.md)*)

![image](https://github.com/phlex-ruby/morphlex/assets/362783/87a6b9c7-94ff-4a45-9533-7eca7c304c71)

## Test 4 - short post → changing 1 character at the end

![image](https://github.com/phlex-ruby/morphlex/assets/362783/5c1fb43a-854d-45ed-bf18-903899e42b70)

## Test 5 - short post → pasting one paragraph at the beginning

![image](https://github.com/phlex-ruby/morphlex/assets/362783/aefb87ab-ccb5-4aa3-9218-f5bb04d4ba90)

## Test 6 - long post → typing 1 word at the end

![image](https://github.com/phlex-ruby/morphlex/assets/362783/d6cd2f70-75e8-43d3-ab01-18f2e62e2cb0)

## Test 7 - long post → typing 1 word in the middle

![image](https://github.com/phlex-ruby/morphlex/assets/362783/3933b9b4-99a9-4d4d-b8f7-634ff3b86f82)

## Test 8 - long post → removing whole paragraph

![image](https://github.com/phlex-ruby/morphlex/assets/362783/dd31fa68-ef2f-47ba-b68d-a45f9a2a9734)

## Test 9 - long post → pasting one paragraph in the middle

![image](https://github.com/phlex-ruby/morphlex/assets/362783/9da0287f-8557-480e-a13e-0841773999f0)

## Test 10 - long post → replacing it with just one paragraph

![image](https://github.com/phlex-ruby/morphlex/assets/362783/b7b569c5-fc5b-4bd3-93ab-b90d584187b3)
